name: Deploy
on:
  push:
    branches:
      - main
jobs:
  create-artifacts:
    name: Create Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Frontend
        run: |
          npm install
          npm run prod
      - name: Configure PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.1'
          extensions: zip, pdo_mysql, gd, json
      - name: Install Composer
        run: |
          composer install --no-dev --no-interaction --prefer-dist
      - name: Create deployment artifacts
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: tar -czf "${GITHUB_SHA}.tar.gz" --exclude=*.git --exclude=node_modules --exclude=tests *
      - name: Store artifacts for distribution
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: ${{ github.sha }}.tar.gz
  prepare-release-on-server:
    name: Prepare Release on Server
    needs: create-artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app-build
      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: ${{ github.sha }}.tar.gz
          target: /home/${{ secrets.USERNAME }}/prostocode.com/www/artifacts/${{ github.sha }}.tar.gz
      - name: Extract artifacts
        uses: appleboy/ssh-action@master
        env:
          RELEASE_PATH: /home/${{ secrets.USERNAME }}/prostocode.com/www/releases/${{ github.sha }}
          ACTIVE_RELEASE_PATH: /home/${{ secrets.USERNAME }}/prostocode.com/www/current
          STORAGE_PATH: /home/${{ secrets.USERNAME }}/prostocode.com/www/storage
          BASE_PATH: /home/${{ secrets.USERNAME }}/prostocode.com/www
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            mkdir -p RELEASE_PATH
            tar xzf ${BASE_PATH}/artifacts/${{ github.sha }}.tar.gz -C $RELEASE_PATH
            ln -s -f ${BASE_PATH}/.env $RELEASE_PATH
            ln -s -f ${BASE_PATH}/storage $RELEASE_PATH
            ln -s -n -f $RELEASE_PATH $ACTIVE_RELEASE_PATH
